name: 'Terraform Azure Deployment'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

      - name: Terraform Plan
        run: terraform plan -var-file="prod_variables.tfvars" \
             -var "subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
             -var "client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
             -var "client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
             -var "tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="prod_variables.tfvars" \
             -var "subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
             -var "client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
             -var "client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
             -var "tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
